{
 "title": "DashBoard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time() - process_start_time_seconds{job=\"prometheus\"})"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "numOfwebsocket" }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "numOfActivewebsockets" }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_cpu_seconds_total" }
   ]
  },
  {
   "title": "Messages Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(numOfMessagewebsockets[1m])  * 60"
    }
   ]
  },
  {
   "title": "ResponseTime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "wsResponseTime" }
   ]
  },
  {
   "title": "process_virtual_memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "decbytes", "label": "Bytes" }
   ],
   "targets": [
    { "expr": "process_virtual_memory_bytes" }
   ]
  }
 ]
}